In [1]:
import numpy as np

In [2]:
myarr = np.diag([1,5,3,7])

In [3]:
myarr

array([[1, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 7]])

In [4]:
import numpy as np

In [6]:
list = [[1,4,7],[2,5,8],[3,6,9]]

In [7]:
myarr2 = np.array(list)

In [8]:
myarr2

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [9]:
# To get the diagonal elements in a two dimesional array we use diag as a function.

In [10]:
np.diag(myarr2)

array([1, 5, 9])