In [1]:
import numpy as np

In [2]:
list = [5,10,15,20,25]

In [3]:
list = np.array(list)

In [4]:
list

array([ 5, 10, 15, 20, 25])

In [5]:
# Slicing with positive number-[:]>[Start : End : Step]

In [6]:
list[0:]

array([ 5, 10, 15, 20, 25])

In [7]:
list[1:]

array([10, 15, 20, 25])

In [8]:
list[1:3]

array([10, 15])

In [9]:
list[:2]

array([ 5, 10])

In [ ]:
# Slicing with negative number

In [10]:
list[:]

array([ 5, 10, 15, 20, 25])

In [12]:
list[-2]

20

In [13]:
list[:-4]

array([5])

In [14]:
list[:-1]

array([ 5, 10, 15, 20])

In [15]:
# [start : end : steps]

In [16]:
list[:]

array([ 5, 10, 15, 20, 25])

In [17]:
list[1:4:1]

array([10, 15, 20])

In [18]:
list[1:2:3]

array([10])

In [ ]:
# Reverse array by

In [20]:
list[:]

array([ 5, 10, 15, 20, 25])

In [24]:
list[::-1]

array([25, 20, 15, 10,  5])