In [1]:
import numpy as np

In [4]:
myarr = np.random.randint(1,100,20)
myarr = myarr.reshape(2,10)
myarr = myarr.reshape(20)

In [5]:
myarr

array([64, 90, 34, 71, 30, 36, 53, 60, 26, 48, 64, 34, 98, 43, 87, 77, 68,
       52, 99, 15])

In [6]:
myarr.ndim

1

In [7]:
myarr.shape

(20,)

In [8]:
# Cheating Multi D Array

In [10]:
myarr = np.random.randint(1,100,50)
myarr = myarr.reshape(10,5)

In [11]:
myarr

array([[88, 18, 98, 66, 25],
       [97, 48, 20, 52, 91],
       [17, 73, 11,  3, 52],
       [56, 82, 13, 28, 52],
       [ 2, 58, 70, 31, 29],
       [86, 79, 86, 88, 86],
       [62, 74,  4, 44, 58],
       [ 2, 61, 69, 34, 95],
       [ 8, 87, 67,  3, 95],
       [ 2, 42, 24, 51, 26]])

In [12]:
myarr.ndim

2

In [13]:
myarr.shape

(10, 5)

In [16]:
myarr = np.random.randint(1,100,50)
myarr = myarr.reshape(2,5,5)

In [17]:
myarr

array([[[96, 59, 47, 36, 91],
        [78, 19, 12, 86, 40],
        [42, 13,  1, 91, 86],
        [68, 12, 21, 13, 40],
        [39, 39, 97,  3, 90]],

       [[56, 45, 14, 22, 63],
        [69, 58, 71, 27, 93],
        [41, 20, 32, 50, 47],
        [84, 73, 50, 77, 22],
        [19, 57, 25, 86, 12]]])

In [18]:
myarr.ndim

3

In [19]:
myarr.shape

(2, 5, 5)