In [1]:
# Creating 2D Array

In [2]:
import numpy as np

In [3]:
myarr = np.array([[5,0,5],[20,25,30],[35,40,45]])

In [4]:
myarr

array([[ 5,  0,  5],
       [20, 25, 30],
       [35, 40, 45]])

In [5]:
# array_nampe[start:end:step,start:end:step]

In [6]:
myarr[0:,0:]

array([[ 5,  0,  5],
       [20, 25, 30],
       [35, 40, 45]])

In [7]:
myarr[:2,:2]

array([[ 5,  0],
       [20, 25]])

In [8]:
myarr[1:,1:]

array([[25, 30],
       [40, 45]])