In [1]:
import numpy as np

In [2]:
myarr=np.random.randint(1,100,10)

In [3]:
myarr

array([81, 13, 14, 89, 61, 30, 48,  6, 41, 16])

In [4]:
# RUN 2nd Time

In [5]:
import numpy as np

In [6]:
myarr=np.random.randint(1,100,10)
myarr

array([30,  3, 69, 64, 26, 59, 57, 28, 50, 27])

In [7]:
# After using Seed Function

In [8]:
import numpy as np

In [9]:
np.random.seed(1)
myarr=np.random.randint(1,100,10)
myarr

array([38, 13, 73, 10, 76,  6, 80, 65, 17,  2])

In [10]:
# RUN 2nd Time

In [11]:
import numpy as np

In [12]:
np.random.seed(9)
myarr=np.random.randint(1,100,10)

In [13]:
myarr

array([93, 55, 57, 23, 66, 23, 53, 60, 41, 92])

In [14]:
myarr.size

10